# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"\x15\n\x05Input\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x16\n\x06Output\x12\x0c\n\x04text\x18\x01 \x01(\t21\n\tAIService\x12$\n\tGetOutput\x12\t.ai.Input\x1a\n.ai.Output\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUT']._serialized_start=16
  _globals['_INPUT']._serialized_end=37
  _globals['_OUTPUT']._serialized_start=39
  _globals['_OUTPUT']._serialized_end=61
  _globals['_AISERVICE']._serialized_start=63
  _globals['_AISERVICE']._serialized_end=112
# @@protoc_insertion_point(module_scope)
